automation:
  - id: huskers_pregame_event
    alias: "Huskers: Pregame Event"
    description: "Start Huskers game-day effect when pregame window opens."
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.huskers_pregame_window
        to: "on"
    condition: []
    action:
      - action: script.huskers_led_gameday_start

  - id: huskers_postgame_event
    alias: "Huskers: Postgame Event"
    description: "Stop Huskers/theater shows when the postgame window closes."
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.huskers_postgame_window
        from: "on"
        to: "off"
    condition: []
    action:
      - action: script.huskers_led_stop

  - id: huskers_touchdown_boost
    alias: "Huskers: Touchdown Boost"
    description: "When our score increases, fire a touchdown burst."
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.huskers_our_score
    condition:
      - condition: template
        value_template: >-
          {{ (trigger.to_state.state | int(0)) > (trigger.from_state.state | int(0)) }}
    action:
      - action: script.huskers_touchdown_burst
