automation:
  - alias: "Huskers: Pregame Event"
    id: huskers_pregame_event
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.huskers_pregame_window
        to: "on"
    action:
      - service: script.huskers_led_gameday_start

  - alias: "Huskers: Postgame Event"
    id: huskers_postgame_event
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.huskers_postgame_window
        to: "on"
    action:
      - service: script.huskers_led_stop

  - alias: "Huskers: Update Last Score (Test)"
    id: huskers_update_last_score_test
    mode: restart
    trigger:
      - platform: state
        entity_id: input_text.huskers_last_score
    action: []

  - alias: "Huskers: React to Test Score"
    id: huskers_react_to_test_score
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.huskers_last_score_test
    action: []

  - alias: "Huskers: New Item Notifier"
    id: huskers_new_item_notifier
    mode: single
    trigger: []
    condition: []
    action: []

  - alias: "Huskers: Theater Show Auto Start"
    id: huskers_theater_show_auto_start
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.huskers_kickoff_in
        below: 21
        above: 19
    action:
      - service: script.huskers_theater_show_start

  - alias: "Huskers: Theater Show Auto Stop"
    id: huskers_theater_show_auto_stop
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.huskers_postgame_window
        from: "on"
        to: "off"
    action:
      - service: script.huskers_theater_show_stop

  - alias: "Huskers: Touchdown Boost"
    id: huskers_touchdown_boost
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.huskers_our_score
    condition:
      - condition: template
        value_template: "{{ (trigger.to_state.state | int(0)) > (trigger.from_state.state | int(0)) }}"
    action:
      - service: script.huskers_touchdown_burst
