extends: default
rules:
  braces: disable
  document-start: disable
  comments:
    min-spaces-from-content: 2
    level: warning
  line-length:
    max: 200
    level: warning
  new-line-at-end-of-file: enable
ignore: |
  node_modules/
  .git/
  .venv/
  .cache/
  zigbee2mqtt/**
  docs/addons/**
  themes/**
  blueprints/**
