extends: default

rules:
  line-length:
    max: 220
  indentation: disable
  hyphens: disable
  comments:
    min-spaces-from-content: 1
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  brackets:
    max-spaces-inside: 1
  braces:
    max-spaces-inside: 1
  comments-indentation: disable
  key-duplicates: enable
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1
