site_name: gate-hub Documentation
site_description: Hypermodern documentation for the gate-hub Home Assistant deployment.
repo_url: https://github.com/dsainz3/gate-hub
nav:
  - Home: index.md
  - How-to Guides:
      - CI Pipeline Runbook: how-to/ci.md
      - Pre-commit Workflow: how-to/pre-commit.md
      - VS Code Dev Container: how-to/dev-container.md
      - Agenda Planner Setup: how-to/agenda-planner.md
      - F1 Weekend Toolkit: how-to/f1/index.md
      - Mosquitto MQTT Add-on: how-to/addons/mqtt.md
      - Govee2MQTT Add-on: how-to/addons/govee2mqtt.md
      - Govee Lighting Stack: how-to/lighting/govee-lighting-stack.md
      - Football Team Dashboard Guide: how-to/football-team/dashboard.md
      - Football Team LED MQTT Controls: how-to/lighting/husker-led-mqtt.md
      - Pre-prod Push Checklist: how-to/pre-prod-checklist.md
      - Kiosk Sanitation Schedule: how-to/kiosk/sanitation-schedule.md
      - Kiosk Camera Overview: how-to/kiosk/camera-overview.md
      - Automated Dashboard Screenshots: how-to/dashboard-screenshots.md
      - Nmap Tracker Debugging: how-to/network/nmap-debugging.md
  - Reference:
      - Documentation Style Guide: reference/documentation-style-guide.md
      - Automation Catalog: reference/automations.md
      - Holiday Mode Reference: reference/holidays.md
      - Basement Theater Media Package: reference/theater-media.md
      - Agenda Planner Reference: reference/agenda-planner.md
      - Infrastructure Overview: reference/infrastructure.md
  - Explanation:
      - Optimization Plan: explanation/optimization-plan.md
      - Football Team Dashboard History: explanation/football-team-dashboard-history.md
      - Pre-commit Quality Strategy: explanation/pre-commit-strategy.md
  - Archive:
      - AI Automation Builder (Archived): archive/ai-automation-builder.md
  - ADRs:
      - Template: adr/_template.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
