# ---- 24h statistics based on KNEPLATT72 sensors ----
- platform: statistics
  name: KNEPLATT72 Wind Speed (24h Avg)
  unique_id: kneplatt72_wind_speed_24h_avg
  entity_id: sensor.kneplatt72_wind_speed
  state_characteristic: mean
  max_age:
    hours: 24

- platform: statistics
  name: KNEPLATT72 Temperature (24h Mean)
  unique_id: kneplatt72_temperature_24h_mean
  entity_id: sensor.kneplatt72_temperature
  state_characteristic: mean
  max_age:
    hours: 24

- platform: statistics
  name: KNEPLATT72 Humidity (24h Mean)
  unique_id: kneplatt72_humidity_24h_mean
  entity_id: sensor.kneplatt72_relative_humidity
  state_characteristic: mean
  max_age:
    hours: 24

- platform: statistics
  name: KNEPLATT72 Pressure (24h Change)
  unique_id: kneplatt72_pressure_24h_change
  entity_id: sensor.kneplatt72_pressure
  state_characteristic: change
  max_age:
    hours: 24

# ---- Pressure trend (rising / steady / falling) ----
- platform: template
  sensors:
    kneplatt72_pressure_trend:
      friendly_name: "KNEPLATT72 Pressure Trend"
      value_template: >-
        {% set u = state_attr('sensor.kneplatt72_pressure','unit_of_measurement') or '' %}
        {% set d = states('sensor.kneplatt72_pressure_24h_change')|float(0) %}
        {% set delta_hpa = d if u in ['hPa','mbar'] else (d * 33.8638866667) %}
        {% if delta_hpa > 0.7 %}rising{% elif delta_hpa < -0.7 %}falling{% else %}steady{% endif %}
      icon_template: >-
        {% set s = states('sensor.kneplatt72_pressure_trend') %}
        {% if s == 'rising' %}mdi:arrow-up-bold
        {% elif s == 'falling' %}mdi:arrow-down-bold
        {% else %}mdi:arrow-right-bold
        {% endif %}
      attribute_templates:
        delta_hpa: >-
          {{ (
              states('sensor.kneplatt72_pressure_24h_change')|float(0) *
              (33.8638866667 if (state_attr('sensor.kneplatt72_pressure','unit_of_measurement') not in ['hPa','mbar']) else 1)
            ) | round(2) }}
        delta_inhg: >-
          {{ (
              (states('sensor.kneplatt72_pressure_24h_change')|float(0) / 33.8638866667)
              if (state_attr('sensor.kneplatt72_pressure','unit_of_measurement') in ['hPa','mbar'])
              else states('sensor.kneplatt72_pressure_24h_change')|float(0)
            ) | round(3) }}
        threshold_hpa: "3.0"

# ---- 24h statistics based on KNEPLATT72 sensors ----
- platform: statistics
  name: KNEPLATT72 Wind Speed (24h Avg)
  unique_id: kneplatt72_wind_speed_24h_avg
  entity_id: sensor.kneplatt72_wind_speed
  state_characteristic: mean
  max_age:
    hours: 24

- platform: statistics
  name: KNEPLATT72 Temperature (24h Mean)
  unique_id: kneplatt72_temperature_24h_mean
  entity_id: sensor.kneplatt72_temperature
  state_characteristic: mean
  max_age:
    hours: 24

- platform: statistics
  name: KNEPLATT72 Humidity (24h Mean)
  unique_id: kneplatt72_humidity_24h_mean
  entity_id: sensor.kneplatt72_relative_humidity
  state_characteristic: mean
  max_age:
    hours: 24

- platform: statistics
  name: KNEPLATT72 Pressure (24h Change)
  unique_id: kneplatt72_pressure_24h_change
  entity_id: sensor.kneplatt72_pressure
  state_characteristic: change
  max_age:
    hours: 24

  # ---- Storm watch if pressure drop > ~3 hPa in 24h ----
  - platform: template
    sensors:
      kneplatt72_storm_watch:
        friendly_name: "KNEPLATT72 Storm Watch"
        value_template: >-
          {% set u = state_attr('sensor.kneplatt72_pressure','unit_of_measurement') or '' %}
          {% set d = states('sensor.kneplatt72_pressure_24h_change')|float(0) %}
          {% set delta_hpa = d if u in ['hPa','mbar'] else (d * 33.8638866667) %}
          {{ delta_hpa < -3.0 }}
        icon_template: >-
          {% if is_state('sensor.kneplatt72_storm_watch','True') %}mdi:weather-cloudy-alert
          {% else %}mdi:weather-sunny
          {% endif %}
        attribute_templates:
          delta_hpa: >-
            {{ (
                states('sensor.kneplatt72_pressure_24h_change')|float(0) *
                (33.8638866667 if (state_attr('sensor.kneplatt72_pressure','unit_of_measurement') not in ['hPa','mbar']) else 1)
              ) | round(2) }}
          threshold_hpa: "3.0"

- platform: template
  sensors:
    huskers_our_score:
      friendly_name: "Nebraska Score"
      value_template: "{{ states('input_number.huskers_our_score') | int(0) }}"
    huskers_opponent_score:
      friendly_name: "Opponent Score"
      value_template: "{{ states('input_number.huskers_opponent_score') | int(0) }}"
    huskers_opponent_name:
      friendly_name: "Opponent Name"
      value_template: "{{ states('input_text.huskers_opponent_name') }}"
    huskers_quarter:
      friendly_name: "Quarter"
      value_template: "{{ states('input_text.huskers_quarter') }}"
    huskers_game_clock:
      friendly_name: "Game Clock"
      value_template: "{{ states('input_text.huskers_game_clock') }}"
    huskers_game_status:
      friendly_name: "Game Status"
      value_template: "{{ states('input_text.huskers_game_status') }}"
