version: 4
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  password: ejos8aiwe6Kookievaa1quahm2BeiBaibai2gah0rei6phub9uBohKee1taezai6
serial:
  port: /dev/ttyUSB0
  adapter: ember
  baudrate: 115200
  rtscts: false
advanced:
  log_level: info
  channel: 11
  network_key:
    - 127
    - 5
    - 250
    - 174
    - 4
    - 8
    - 243
    - 165
    - 166
    - 68
    - 31
    - 236
    - 82
    - 164
    - 204
    - 156
  pan_id: 33793
  ext_pan_id:
    - 36
    - 84
    - 59
    - 145
    - 37
    - 95
    - 148
    - 88
frontend:
  enabled: true
  port: 8099
homeassistant:
  enabled: true
devices:
  '0xb4e8429127eb0000':
    friendly_name: Light-Under-Stairs
  '0xc890a81f210a0000':
    friendly_name: Light-Theater-Right
  '0xc890a81f2eca0000':
    friendly_name: Light-Theater-Left
  '0xffffb40e0600a354':
    friendly_name: Plug-basement-burner
  '0x1c784ba0eeff0000':
    friendly_name: Light-Front-left
  '0x1c784ba0b2150000':
    friendly_name: Light-Front-right
  '0x282c02bfffefd159':
    friendly_name: Plug-humidor
  '0xa4c13809f17a19a6':
    friendly_name: Hygrometer-Humidor
  '0x282c02bfffeff4c6':
    friendly_name: Plug-Mainfloor-burner
  '0x187a3efffec58181':
    friendly_name: Sensor-office
  '0x282c02bfffeff7c5':
    friendly_name: Plug-bedroom-burner
  '0x1c784ba10cbf0000':
    friendly_name: light-garage-left
  '0xc890a81ee8610000':
    friendly_name: Light-garage-center
  '0xc890a81ee1de0000':
    friendly_name: Light-garage-right
  '0x1c784ba0ecf80000':
    friendly_name: Light-office
groups:
  '1':
    friendly_name: ZB Group External Lights
  '3':
    friendly_name: ZB Group Basement Lights
