version: 4
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  password: ejos8aiwe6Kookievaa1quahm2BeiBaibai2gah0rei6phub9uBohKee1taezai6
serial: {}
advanced:
  log_level: info
  channel: 11
  network_key: GENERATE
  pan_id: GENERATE
  ext_pan_id: GENERATE
frontend:
  enabled: true
  port: 8099
homeassistant:
  enabled: true
onboarding: true
