# packages/holidays.yaml
# US holiday calendar feed plus helpers for manual overrides.

input_boolean:
  holiday_mode_manual:
    name: Holiday Mode Override
    icon: mdi:calendar-star

template:
  - binary_sensor:
      - name: Holiday Mode Active
        unique_id: holiday_mode_active
        state: >-
          {{ is_state('calendar.us_federal_holidays', 'on') or is_state('input_boolean.holiday_mode_manual', 'on') }}
        icon: >-
          {% if is_state('input_boolean.holiday_mode_manual', 'on') %}
            mdi:calendar-star
          {% elif is_state('calendar.us_federal_holidays', 'on') %}
            mdi:calendar-check
          {% else %}
            mdi:calendar-blank
          {% endif %}
        attributes:
          holiday_source: >-
            {% if is_state('input_boolean.holiday_mode_manual', 'on') %}
              manual
            {% elif is_state('calendar.us_federal_holidays', 'on') %}
              calendar
            {% else %}
              none
            {% endif %}
          active_holiday: >-
            {% if is_state('input_boolean.holiday_mode_manual', 'on') and not is_state('calendar.us_federal_holidays', 'on') %}
              Manual Override
            {% elif is_state('calendar.us_federal_holidays', 'on') %}
              {{ state_attr('calendar.us_federal_holidays', 'message') | default('Holiday', true) }}
            {% else %}
              none
            {% endif %}
          active_until: >-
            {% if is_state('calendar.us_federal_holidays', 'on') %}
              {{ state_attr('calendar.us_federal_holidays', 'end_time') | default('unknown', true) }}
            {% else %}
              unknown
            {% endif %}
  - sensor:
      - name: Next US Holiday
        unique_id: next_us_holiday
        state: >-
          {% set next_name = state_attr('calendar.us_federal_holidays', 'message') %}
          {% set next_start = state_attr('calendar.us_federal_holidays', 'start_time') %}
          {% if next_start and next_name %}
            {{ next_name }}
          {% elif next_start %}
            Holiday
          {% else %}
            unavailable
          {% endif %}
        availability: >-
          {{ state_attr('calendar.us_federal_holidays', 'start_time') is not none }}
        attributes:
          starts_on: >-
            {% set next_start = state_attr('calendar.us_federal_holidays', 'start_time') %}
            {% if next_start %}
              {{ as_datetime(next_start) | as_local | isoformat }}
            {% else %}
              unknown
            {% endif %}
          ends_on: >-
            {% set next_end = state_attr('calendar.us_federal_holidays', 'end_time') %}
            {% if next_end %}
              {{ as_datetime(next_end) | as_local | isoformat }}
            {% else %}
              unknown
            {% endif %}

script:
  test_halloween:
    alias: Test Halloween
    description: Rotate Halloween colors across theater and sunroom lights.
    mode: restart
    sequence:
      - repeat:
          while:
            - condition: template
              value_template: "{{ true }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_theater_left
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 255
                  - 110
                  - 0
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_theater_right
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 180
                  - 40
                  - 220
            - service: light.turn_on
              target:
                entity_id:
                  - light.sunroom_light
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 220
                  - 50
                  - 50
            - delay:
                seconds: 5

  holiday_exterior_lights:
    alias: Holiday Exterior Lights
    description: Rotate exterior front and garage lights through Halloween colors.
    mode: restart
    sequence:
      - repeat:
          while:
            - condition: template
              value_template: "{{ true }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_front_left
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 255
                  - 110
                  - 0
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_front_right
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 180
                  - 40
                  - 220
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_garage_left
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 220
                  - 50
                  - 50
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_garage_center
              data:
                brightness_pct: 70
                transition: 5
                rgb_color:
                  - 0
                  - 140
                  - 20
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_garage_right
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 230
                  - 120
                  - 10
            - delay:
                seconds: 5
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_front_left
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 180
                  - 40
                  - 220
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_front_right
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 220
                  - 50
                  - 50
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_garage_left
              data:
                brightness_pct: 70
                transition: 5
                rgb_color:
                  - 0
                  - 140
                  - 20
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_garage_center
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 230
                  - 120
                  - 10
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_garage_right
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 255
                  - 110
                  - 0
            - delay:
                seconds: 5
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_front_left
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 220
                  - 50
                  - 50
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_front_right
              data:
                brightness_pct: 70
                transition: 5
                rgb_color:
                  - 0
                  - 140
                  - 20
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_garage_left
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 230
                  - 120
                  - 10
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_garage_center
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 255
                  - 110
                  - 0
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_garage_right
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 180
                  - 40
                  - 220
            - delay:
                seconds: 5
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_front_left
              data:
                brightness_pct: 70
                transition: 5
                rgb_color:
                  - 0
                  - 140
                  - 20
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_front_right
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 230
                  - 120
                  - 10
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_garage_left
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 255
                  - 110
                  - 0
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_garage_center
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 180
                  - 40
                  - 220
            - service: light.turn_on
              target:
                entity_id:
                  - light.light_garage_right
              data:
                brightness_pct: 75
                transition: 5
                rgb_color:
                  - 220
                  - 50
                  - 50
            - delay:
                seconds: 5

  holiday_exterior_lights_resume:
    alias: Holiday Exterior Lights Resume
    description: Stop the holiday rotation and reapply scheduled exterior lighting automations.
    mode: single
    sequence:
      - service: script.turn_off
        target:
          entity_id: script.holiday_exterior_lights
      - delay:
          seconds: 1
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ is_state('sun.sun', 'below_horizon') and now() >= today_at('03:30:00') }}
            sequence:
              - service: light.turn_on
                target:
                  entity_id:
                    - light.front_porch_lights
                    - light.light_garage_left
                    - light.light_garage_center
                    - light.light_garage_right
                data:
                  color_temp: 500
                  brightness_pct: 10
                  transition: 3
              - if:
                  - condition: template
                    value_template: "{{ has_value('light.permanent_outdoor_lights') }}"
                then:
                  - service: light.turn_on
                    target:
                      entity_id: light.permanent_outdoor_lights
                    data:
                      brightness_pct: 50
                      transition: 3
                    continue_on_error: true
        default:
          - service: light.turn_off
            target:
              entity_id:
                - light.front_porch_lights
                - light.light_garage_left
                - light.light_garage_center
                - light.light_garage_right
            data:
              transition: 5
          - if:
              - condition: template
                value_template: "{{ has_value('light.permanent_outdoor_lights') }}"
            then:
              - service: light.turn_off
                target:
                  entity_id: light.permanent_outdoor_lights
                data:
                  transition: 5
                continue_on_error: true

automation:
  - id: activate_halloween_exterior_lights
    alias: Activate Halloween Exterior Lights
    description: Start the Halloween exterior rotation at midnight on Halloween.
    trigger:
      - platform: time
        at: "00:00:00"
    condition:
      - condition: template
        value_template: "{{ now().month == 10 and now().day == 31 }}"
    action:
      - service: script.turn_on
        target:
          entity_id: script.holiday_exterior_lights
      - service: logbook.log
        data:
          name: Holiday Automation
          message: Halloween exterior lights start sequence triggered
          entity_id: automation.activate_halloween_exterior_lights
    mode: single

  - id: deactivate_halloween_exterior_lights
    alias: Deactivate Halloween Exterior Lights
    description: Stop the Halloween exterior rotation at midnight after Halloween.
    trigger:
      - platform: time
        at: "00:00:00"
    condition:
      - condition: template
        value_template: "{{ now().month == 11 and now().day == 1 }}"
    action:
      - service: script.turn_on
        target:
          entity_id: script.holiday_exterior_lights_resume
      - service: logbook.log
        data:
          name: Holiday Automation
          message: Halloween exterior lights resume sequence triggered
          entity_id: automation.deactivate_halloween_exterior_lights
    mode: single

  - id: holiday_mode_manual_reset
    alias: 'Holiday Mode: Reset Manual Override'
    description: Turn off the manual holiday mode flag once the calendar is clear.
    trigger:
      - platform: state
        entity_id: calendar.us_federal_holidays
        to: 'off'
      - platform: time
        at: '23:30:00'
      - platform: homeassistant
        event: start
      - platform: time_pattern
        minutes: '/30'
    condition:
      - condition: state
        entity_id: calendar.us_federal_holidays
        state: 'off'
      - condition: state
        entity_id: input_boolean.holiday_mode_manual
        state: 'on'
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.holiday_mode_manual
      - service: logbook.log
        data:
          name: Holiday Automation
          message: Manual holiday override cleared (calendar off)
          entity_id: automation.holiday_mode_manual_reset
    mode: restart

  - id: holiday_mode_manual_reset_2330
    alias: 'Holiday Mode: 11:30 PM Reset'
    description: Ensure the manual holiday override is cleared each night at 11:30 PM.
    trigger:
      - platform: time
        at: '23:30:00'
    condition:
      - condition: state
        entity_id: input_boolean.holiday_mode_manual
        state: 'on'
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.holiday_mode_manual
      - service: logbook.log
        data:
          name: Holiday Automation
          message: Manual holiday override cleared at 23:30
          entity_id: automation.holiday_mode_manual_reset_2330
    mode: single
