name: AI - Generate Automation PR

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Describe the automation you want (plain English)'
        required: true
      file_slug:
        description: 'File name (no spaces). Example: door_notify'
        required: false
        default: 'ai_automation'
      outdir:
        description: 'Target directory'
        required: false
        default: 'packages/ai'
      model:
        description: 'OpenAI model'
        required: false
        default: 'gpt-4o-mini'
      dry_run:
        description: 'Parse only (no PR)'
        required: false
        default: 'false'

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install openai pyyaml

      - name: Generate YAML with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python tools/ai_automation/generate.py             --prompt "${{ inputs.prompt }}"             --outdir "${{ inputs.outdir }}"             --slug "${{ inputs.file_slug }}"             --model "${{ inputs.model }}"             $([ "${{ inputs.dry_run }}" = "true" ] && echo "--dry-run" || true)

      - name: Create Pull Request
        if: inputs.dry_run != 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: 'ai/auto-${{ inputs.file_slug }}'
          title: 'AI: ${{ inputs.file_slug }} automation'
          commit-message: 'AI: add ${{ inputs.file_slug }} automation'
          body: |
            Generated from prompt:

            ```
            ${{ inputs.prompt }}
            ```
          add-paths: |
            packages/ai/**
            automations/**
