name: CI

'on':
  push:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Optional cache to speed up pre-commit envs
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

      # This runs ALL hooks you configured (prettier, yamllint, HA check, etc.)
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
