name: CI

'on':
  push:
    branches:
      - main
      - develop
      - feature/**
      - chore/**
      - fix/**
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up Node (for Prettier hooks)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache pre-commit envs
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

      - name: Install pre-commit
        run: python -m pip install --upgrade pip pre-commit

      - name: Run pre-commit (skip HA check in CI)
        env:
          SKIP: hass-config-check
        run: pre-commit run --all-files --show-diff-on-failure

  home-assistant-config:
    name: Home Assistant config check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Ensure a placeholder secrets.yaml exists if your config expects it
      - name: Ensure secrets.yaml exists
        run: |
          if [ ! -f secrets.yaml ]; then
            echo "# CI placeholder" > secrets.yaml
          fi

      - name: Run Home Assistant check_config
        uses: frenck/action-home-assistant@v1
        with:
          path: '.'
          # Keep this aligned with your HA Core version if desired
          version: '2025.8.2'
