name: CI

on:
  pull_request:
    branches: [main]
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '.pre-commit-config.yaml'
      - 'pyproject.toml'
      - 'poetry.lock'
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pipx install poetry
      - name: Configure Poetry
        run: poetry config virtualenvs.create false
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files

  ha-config-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create secrets stub
        run: cp secrets.example.yaml secrets.yaml || true
      - name: YAML lint
        run: poetry run yamllint -s .
      - name: HA config check
        run: |
          docker run --rm -v "$PWD":/config ghcr.io/home-assistant/home-assistant:stable \
            python -m homeassistant --script check_config --config /config
