name: Home Assistant - Config Check

'on':
  pull_request:
    branches:
      - main
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.json'
      - 'dashboards/**'
      - 'packages/**'
      - 'custom_components/**'
      - 'configuration.yaml'
      - 'themes.yaml'
      - '.github/workflows/ha-config-check.yml'
  push:
    branches:
      - main
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.json'
      - 'dashboards/**'
      - 'packages/**'
      - 'custom_components/**'
      - 'configuration.yaml'
      - 'themes.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-config:
    name: Validate HA configuration
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare CI environment (use .ci/fakesecrets.yaml if available)
        shell: bash
        run: |
          set -euo pipefail
          cd "${{ github.workspace }}"

          if [ -f .ci/fakesecrets.yaml ]; then
            cp .ci/fakesecrets.yaml secrets.yaml
            echo "Using .ci/fakesecrets.yaml for CI"
          elif [ -f fakesecrets.yaml ]; then
            cp fakesecrets.yaml secrets.yaml
            echo "Using fakesecrets.yaml for CI"
          else
            [[ -f secrets.yaml ]] || echo "# auto-generated by CI (empty)" > secrets.yaml
            echo "No fakesecrets.yaml found; using existing or empty secrets.yaml"
          fi

          # Create common include files if referenced but missing
          for f in automations.yaml scripts.yaml customize.yaml; do
            if grep -Rql "$f" configuration.yaml 2>/dev/null || grep -Rql "$f" . 2>/dev/null; then
              [[ -f "$f" ]] || touch "$f"
            fi
          done

          echo "---- secrets.yaml (first 40 lines) ----"
          sed -n '1,40p' secrets.yaml || true

      - name: Pull Home Assistant container
        run: docker pull ghcr.io/home-assistant/home-assistant:stable

      - name: Run hass --script check_config (with full output)
        env:
          TZ: America/Chicago
        run: |
          set -o pipefail
          docker run --rm \
            -e TZ \
            -v "${{ github.workspace }}":/config \
            ghcr.io/home-assistant/home-assistant:stable \
            python -m homeassistant --config /config --script check_config | tee check_config.out

      - name: Upload diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ha-check-config-output
          path: check_config.out
