name: HA Config Check

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ha-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Home Assistant Core Configuration Check
        uses: frenck/action-home-assistant@v1
        with:
          path: "."
          secrets: "fakesecrets.yaml"
          # version: stable