name: Lint

'on':
  pull_request:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
      - pyproject.toml
      - .pre-commit-config.yaml
      - .yamllint.yml
      - '**/*.yml'
      - '**/*.yaml'

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    name: Ruff (lint + format check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install ruff
      - name: ruff check
        run: ruff check . --output-format=github --force-exclude
      - name: ruff format --check
        run: ruff format --check .

  precommit:
    name: pre-commit (YAML & HA tools)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pre-commit
      - name: pre-commit run (non-Python hooks)
        env:
          SKIP: ruff,ruff-format,black,flake8
        run: pre-commit run --all-files
