name: Seed HA Optimization Issues

'on':
  workflow_dispatch:
    inputs:
      plan_path:
        description: 'Path to the Markdown plan'
        required: true
        default: '.github/seed/ha-issues.md'
      project_id:
        description: 'Optional Project v2 ID (e.g., PVT_kwHOBOLd8c4BBFBV)'
        required: false
        default: ''
      create_branches:
        description: 'Create branches listed in the plan'
        required: false
        default: 'false'
      base_branch:
        description: 'Base branch for new branches'
        required: false
        default: 'main'
      dry_run:
        description: 'Only parse; no writes'
        required: false
        default: 'false'

# ✅ Valid permissions:
permissions:
  contents: write
  issues: write

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Seed issues from plan
        uses: actions/github-script@v7
        with:
          # 👇 Use your PAT secret (classic) with scopes: repo, project, read:org
          github-token: ${{ secrets.ISSUES_TOKEN }}
          script: |
            // ... your existing Node script exactly as you had it ...
